LEG_DECORATIONS = {
    'Plastisol other':'Plastisol Transfer',
    'Sublimation BAGS':'Sublimation',
    'Large Format Screenprinting':'Screen Print',
    'Screen Printing 3 Colour':'Screen Print',
    'Supacolour Apparel':'Sublimation',
    'Laser Etching - 25mm x 30mm':'Laser Etch',
    'Screen Printing 1 Colour':'Screen Print',
    'Supacolour UMBRELLAS':'Sublimation',
    'Digital Transfer other':'Digital Transfer',
    'Supacolour':'Sublimation',
    'Screen Printing COMPENDIUM':'Screen Print',
    'Sublimation M170 only':'Sublimation',
    'Screen Printing 4 Colour':'Screen Print',
    'Screen Printing 2 Colour':'Screen Print',
    'Screen Print Non-woven':'Screen Print',
    'Screen Printing APPAREL':'Screen Print',
    'Supacolour Non-Woven':'Sublimation',
    'Embroidery':'Embroidery',
    'Laser Etching':'Laser Etch',
    'Screen Print':'Screen Print',
    'Digital Transfer':'Digital Transfer',
    'Plastisol Transfer':'Plastisol Transfer'
}



# Dictionary mapping Legend Colour codes to Brand Elevate
LEG_to_BE = {
    'Aqua':'AQ','Arctic':'AQ','Turquoise':'AQ','Black':'BK','Black Opal':'BK','Blue':'BL',
     'Bright Royal':'BL','Dark Royal':'BL','Hawaii Blue':'BL','Light Blue':'AQ','Marina Blue':'BL',
     'Powder Blue':'BL','Process Blue':'AQ','Royal':'BL','Sky Blue':'BL','Teal':'BL','True Blue':'BL',
     'Vintage Blue':'BL','Camouflage':'BR','Chestnut':'BR','Dark Brown':'BR','Espresso':'BR','Khaki':'BR',
     'Tuscan Brown':'BR','Vintage Brown':'BR','Brown':'BR','Cream':'CR','Light Tan':'CR','Natural':'CR',
     'Tan':'CR','Bottle':'GR','Bottle Green':'GR','Camouflage Green':'GR','Dark Grey':'GR','Emerald':'GR',
     'Forest Green':'GR','Green':'GR','Kelly Green':'GR','Loden Green':'GR','Vintage':'GR','Ash Grey':'GY',
     'Charcoal':'CH','Cool Grey':'GY','Grey':'GY','Grey Marle':'GY','Slate Grey':'GY','Smoke':'GY',
     'Stone':'GY','Vintage Grey':'GY','Desert':'LBR','Safari':'LBR','Sandstone':'LBR','Taupe':'LBR',
     'Apple Green':'LGR','Lime':'LGR','Burgundy':'MA','Dark Maroon':'MA','Maroon':'MA','Blue Midnight':'NA',
     'Midnight Blue':'NA','Navy':'NA','Olive':'OL','Burnt Orange':'OR','Mustard':'OR','Ochre':'OR',
     'Orange':'OR','Tangerine Orange':'OR','Hot Pink':'PK','Light Pink':'PK','Pastel Pink':'PK','Pink':'PK',
     'Strawberry Pink':'PK','Vintage Rose':'PK','Lavender':'PU','Plum':'PU','Purple':'PU','Crimson Red':'RD',
     'Antique Cherry':'RD','Red':'RD','Red Tartan':'RD','Santa FE Red':'RD','Scarlet Red':'RD',
     'Grey Heather':'SI','Silver':'SI','Steel':'SI','Light Grey':'GY','Chalk White':'WH','Snow':'WH',
     'White':'WH','Gold':'YE','Hi Vis Yellow':'YE','Yellow':'YE','Light Royal R':'RD'}
# legend_map is a dictionary mapping fields direct through to the Magento import.

LEGEND_MAP = {
    #'product_code':'sku',
    # '':'store_view_code',
    # 'Default':'attribute_set_code',
    # '':'product_type',
    # 'categorisation':'categories',
    # 'base':'product_websites',
    # 'product_name':'name',
    #'product_description':'description',
    #'':'short_description',
    #####'product_features':'short_description',
    # '1':'weight',
    # '1':'product_online',
    # 'Taxable Goods':'tax_class_name',
    # '':'visibility',
    'price_1':'price',
    # '':'special_price',
    # '':'special_price_from_date',
    # '':'special_price_to_date',
    # 'sku':'url_key',
    'product_name':'meta_title',
    ########'additional_keywords':'meta_keywords'
    #'':'meta_keywords',
    #'product_description':'meta_description',
    # 'product_image_file_name':'base_image',
    # '':'base_image_label',
    # 'product_image_file_name':'small_image',
    # '':'small_image_label',
    # 'product_image_file_name':'thumbnail_image',
    # '':'thumbnail_image_label',
    # 'product_image_file_name':'swatch_image',
    # '':'swatch_image_label',
    # '':'created_at',
    # '':'updated_at',
    # '':'new_from_date',
    # '':'new_to_date',
    # 'Block after Info Column':'display_product_options_in',
    # '':'map_price',
    # '':'msrp_price',
    # '':'map_enabled',
    # '':'gift_message_available',
    # '':'custom_design',
    # '':'custom_design_from',
    # '':'custom_design_to',
    # '':'custom_layout_update',
    # '':'page_layout',
    # '':'product_options_container',
    # '':'msrp_display_actual_price_type',
    # '':'country_of_manufacture',
    'carton_height':'carton_height',
    'carton_depth':'carton_depth',
    'carton_width':'carton_width',
    'carton_weight':'carton_weight',
    'carton_qty':'carton_qty',
    'carton_cubic':'carton_cubic',
    # '':'carton_notes',
    'freight_description':'freight_description',
    # 'product_sizes':'size',
    'branded':'branded',
    # '':'climate',
    # 'colours_available_supplier':'color',
    'decoration_areas':'decoration_areas',
    #'decoration_options_available':'decoration_options_available',
    #'decoration_type':'decoration_type',
    'label_name':'manufacturer',
    # '':'pattern',
    # '0':'featured',
    'catalogue_name':'catalogue_name',
    #'indent_only':'indent_only',
    'price_decoration_description':'price_decoration_description',
    # '':'product_features',
    'product_URL':'supplier_product_url',
    # '40':'markup_per',
    # '':'product_packaging_inner',
    'brand_name':'seller',
    # '':'gender',
    # 'product_materials':'product_material',
    # '':'additional_attributes',
    # '1000':'qty',
    #'discontinued_stock':'out_of_stock_qty',
    # '1':'use_config_min_qty',
    # '0':'is_qty_decimal',
    # '0':'allow_backorders',
    # '1':'use_config_backorders',
    'MOQ':'min_cart_qty',
    # '1':'use_config_min_sale_qty',
    # '10000':'max_cart_qty',
    # '1':'use_config_max_sale_qty',
    # '1':'is_in_stock',
    # '':'notify_on_stock_below',
    # '1':'use_config_notify_stock_qty',
    # '1':'manage_stock',
    # '1':'use_config_manage_stock',
    # '1':'use_config_qty_increments',
    # '2':'qty_increments',
    # '1':'use_config_enable_qty_inc',
    # '0':'enable_qty_increments',
    # '0':'is_decimal_divided',
    # '0':'website_id',
    # '':'related_skus',
    # '':'related_position',
    # '':'crosssell_skus',
    # '':'crosssell_position',
    # '':'upsell_skus',
    # '':'upsell_position',
    #'alternate_views_image_file_names':'additional_images',
    # '':'additional_image_labels',
    # '':'hide_from_product_page',
    # '':'custom_options',
    # '':'bundle_price_type',
    # '':'bundle_sku_type',
    # '':'bundle_price_view',
    # '':'bundle_weight_type',
    # '':'bundle_values',
    # '':'bundle_shipment_type',
    # '':'configurable_variations',
    # '':'configurable_variation_labels',
    # '':'associated_skus'
    }
